### ISSUE TITLE
Virtual Environment

### ISSUE THREAD

**Issue by bezzamlmc** [ebezzam/python-dev-tips#2]
Explain the benefits of using a virtual environment (btw, let's see if it is possible to organize the issues under Projects).

**Comment by ebezzam** [comment]
Good point, a small comment on the benefits of each aspect could be useful. Some are explained in these [interactive slides](https://docs.google.com/presentation/d/1BnezhwUy22DiF72wss8GU_YIMfhjortz-uILdIFGuoM/edit#slide=id.p) (page 9 for virtual environment motivation).

**Comment by bezzamlmc** [comment]
Years back it was Anaconda's Spider vs Enthought Canopy. I used canopy because of its nice Mayavi 3D libray (https://docs.enthought.com/ets/?_ga=2.171382307.2074152626.1673762533-231344295.1673762533) After VS Code came about Canopy is now gone. Enthought's libraries still around.

**Comment by ebezzam** [comment]
There's a brief explanation on the benefits of virtual environments in the [revamped documentation](https://pydevtips.readthedocs.io/en/latest/virtual_env.html).
